name: Run Mount S3 files to container
on:
  push:
    branches: [ main ]

jobs:
  run-debian-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build image
        run: |
          cd debian
          docker build . -t s3fuse-test --build-arg BUCKET_NAME=${{secrets.BUCKET_NAME}}

      - name: Run Docker container
        run: docker run -t -e ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID}} -e SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY}} --privileged s3fuse-test

  run-alpine-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build image
      run: |
        cd alpine
        docker build . -t s3fuse-test --build-arg BUCKET_NAME=${{secrets.BUCKET_NAME}}
    
    - name: Run Docker container
      run: docker run -t -e ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID}} -e SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY}} --privileged s3fuse-test

  run-amzn-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build image
        run: |
          cd amzn
          docker build . -t s3fuse-test --build-arg BUCKET_NAME=${{secrets.BUCKET_NAME}}

      - name: Run Docker container
        run: docker run -t -e ACCESS_KEY_ID=${{secrets.ACCESS_KEY_ID}} -e SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY}} --privileged s3fuse-test
